# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lA3umDTRwr-ijeEOos8GArMhdVKfwTBx
"""

import pandas as pd
teachers=pd.DataFrame({
    "FISH":[ 'QADAMOVA Z',"xalilov D","Djalilov M","Qurbonova G","Turdimatov M","Raxmatov R","Jorayeva G","Tillaboyev M","Xontorayev S","Abdullayeva M"],
    "Fani":["sun'iy intelekt asoslari","sun'iy intelekt asoslari","Kompyuterni tashkil etish","Kompyuterni tashkil etish","kiberxavfsizlik asoslari","kiberxavfsizlik asoslari","Elektron sxemalar","Elektron sxemalar","Malumotlar tuzilmasi va algoritmlar","Malumotlar tuzilmasi va algoritmlar"],
    "Mashg'ulot turi":['amamliy','maruza','maruza','amamliy','maruza','amamliy','maruza','amamliy','maruza','amamliy'],
    "Dars o'tish maxorati":['yaxshi','yaxshi','yaxshi','yaxshi','yaxshi','yaxshi','yaxshi','yaxshi','yaxshi','yaxshi'],

})
print(teachers)

teachers.to_excel("mamadaliyev571.xlsx")